function policies = systems_policy_catalog(policySet, cfg)
%SYSTEMS_POLICY_CATALOG Pure plan-inertia factorial policy definitions.
% The 2x2 factorial cells differ only in (i) event-gated versus always
% planning access and (ii) fixed versus adaptive plan inertia. Event cells
% always use the same threshold stored in cfg.EventWindThresholdMps.

    if nargin < 1 || isempty(policySet), policySet = 'factorial5'; end
    if nargin < 2 || isempty(cfg), cfg = systems_default_config(); end

    alwaysFixed = make_policy('AlwaysFixed', ...
        'Always-RHO, fixed W_3', 'always', false, cfg.FixedW3, NaN, ...
        'factorial');
    etFixed = make_policy('ETFixed', ...
        'ET-RHO, fixed W_3', 'event', false, cfg.FixedW3, ...
        cfg.EventWindThresholdMps, 'factorial');
    alwaysAdaptive = make_policy('AlwaysAdaptive', ...
        'Always-RHO, adaptive W_3(k)', 'always', true, cfg.W3base, NaN, ...
        'factorial');
    etAdaptive = make_policy('ETAdaptive', ...
        'Proposed ET-RHO, adaptive W_3(k)', 'event', true, cfg.W3base, ...
        cfg.EventWindThresholdMps, 'factorial');
    alwaysMyopic = make_policy('AlwaysMyopic', ...
        'Always-RHO, no plan inertia', 'always', false, 0, NaN, ...
        'nonfactorial-reference');

    switch lower(string(policySet))
        case {"factorial5", "headline5"}
            policies = [alwaysFixed, etFixed, alwaysAdaptive, etAdaptive, ...
                alwaysMyopic];
        case "factorial4"
            policies = [alwaysFixed, etFixed, alwaysAdaptive, etAdaptive];
        case {"core2", "matched2"}
            policies = [etFixed, etAdaptive];
        case {"gate2", "access2"}
            % Main boundary contrast: isolate ordinary planning access while
            % holding the fixed inertia specification constant.
            policies = [alwaysFixed, etFixed];
        otherwise
            error('systems_policy_catalog:UnknownSet', ...
                'Unknown policySet "%s".', string(policySet));
    end
    keys = {policies.Key};
    assert(numel(unique(keys)) == numel(keys), ...
        'systems_policy_catalog:DuplicateKey', 'Policy keys must be unique.');
end

function p = make_policy(key, name, triggerMode, adaptive, fixedW3, ...
        threshold, statisticalRole)
    p = struct('Key', key, 'Name', name, 'TriggerMode', triggerMode, ...
        'Adaptive', adaptive, 'FixedW3', fixedW3, ...
        'WindThresholdMps', threshold, ...
        'StatisticalRole', statisticalRole);
end
