function spatial = load_public_spatial_zones()
%LOAD_PUBLIC_SPATIAL_ZONES Load the fixed abstract public demand zones.
% Generated by scripts/build_public_calibration.py. The 12 centres were fit
% on Olist calibration data only. They are not customer addresses, a depot,
% truck positions, roads or authorised aerial corridors.

    here = fileparts(mfilename('fullpath'));
    sourceFile = fullfile(here, '..', 'processed', 'olist_12_zone_geometry.csv');
    zones = readtable(sourceFile, 'TextType', 'string');
    zones = sortrows(zones, 'zone_id');
    if height(zones) ~= 12
        error('Expected 12 public spatial zones, found %d.', height(zones));
    end
    if any(zones.calibration_probability <= 0) || abs(sum(zones.calibration_probability) - 1) > 1e-10
        error('Spatial-zone probabilities must be positive and sum to one.');
    end

    spatial.ZoneId = zones.zone_id;
    spatial.CoordKm = [zones.x_km_from_demand_center, zones.y_km_from_demand_center];
    spatial.Probability = zones.calibration_probability';
    spatial.DemandCentreKm = [0, 0];
    spatial.FitSplit = 'calibration';
    spatial.HoldoutTVD = 0.040845;
    spatial.Contract = ['Use CoordKm only as abstract demand-zone geometry. ', ...
        'Set the V2 platform start explicitly; [0,0] is only the demand-centre reference.'];
end
